---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# make sure namespace exists
resources:
- namespace.yaml

# custom index.html file


#vault helm chart
helmChartInflationGenerator:
- chartName: argocd
  chartRepoUrl: https://argoproj.github.io/argo-helm
  chartVersion: 5.30.0
  releaseName: argocd
  releaseNamespace: argocd
  # override with these custom values
  values: values.yaml

generatorOptions:
  disableNameSuffixHash: true
